### ISSUE TITLE
Replace bolt argument nodes with targets

### ISSUE THREAD

**Issue by findmyname666** [oscar-stack/vagrant-bolt#13]
Hello there, 

Bolt argument **--nodes** has been replaced by **--target** and it doesn't work with newer versions. The same applies also for inventory:
```
==> agent: Running provisioner: puppet_agent::install (bolt)...
==> agent: Bolt: Running bolt command locally: /opt/puppetlabs/bin/bolt task run 'puppet_agent::install' --boltdir '.' --private-key '~/.vagrant.d/insecure_private_key' --run-as 'root' --params '{"stop_service":true}' --inventoryfile '.vagrant/bolt_inventory.yaml' --targets 'agent'
==> agent: Found 'nodes' key in group all. This looks like a v1 inventory file, which is
==> agent: no longer supported by Bolt. Migrate to a v2 inventory file automatically using
==> agent: 'bolt project migrate'.
==> agent:
```
I don't have an error output from **--nodes** because i already hot-patched it locally.

Can we rework it pls?

**Comment by jarretlavallee** [comment]
@findmyname666 Thanks for submitting this. #12 was merged the other day and I will get a new release out shortly.

**Comment by jarretlavallee** [comment]
https://rubygems.org/gems/vagrant-bolt/versions/0.2.0 has been released. Let me know if there are any issues with the new build.
